language: cpp
dist: xenial
compiler: gcc

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

script: 
  - cmake CMakeLists.txt
  #- cmake -D CMAKE_C_COMPILER=gcc-5 -D CMAKE_CXX_COMPILER=g++-5 CMakeLists.txt
  - make
  - ./travis_cmake_gcc_cpp14_boost
